### PR TITLE
Log level

### PR DESCRIPTION
**Pull request by calvin620707**

### CODE REVIEW

**Review by wucj — APPROVED** [review]

**Comment by jonascheng** [comment]
Travis CI failed?

**Comment by calvin620707** [comment]
死在pip的樣子

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-J4MA9i/distribute/
The command "pip install -r requirements.txt" failed and exited with 1 during .

**Comment by jonascheng** [comment]
failed again?

**Comment by calvin620707** [comment]
https://travis-ci.org/drmobile/dynamodb-titan/builds/243610270

應該不是code change的問題, 跑之前已經pass的Travis CI task也fail

**Comment by calvin620707** [comment]
Open an [issue](https://github.com/travis-ci/travis-ci/issues/8105) for Travis CI

**Comment by calvin620707** [comment]
@jonascheng 這個3個月前的PR終於workaround把CI修好了~

**Pull request merged**
